### ISSUE TITLE
Use maven 'copy-dependencies' to copy jars to Fluo application lib

### ISSUE THREAD

**Issue by mikewalch** [astralway/webindex#93]
Currently `webindex init` copies needed jars to the Fluo app lib using the Maven command below:
```bash
mvn dependency:get -Dartifact=org.apache.fluo:fluo-recipes-core:1.0.0-incubating-SNAPSHOT:jar -Ddest=$FLUO_APP_LIB
```
It would be better if the version did not have be included using the command below (copied from the change @keith-turner made to stresso):

```bash
mvn dependency:copy-dependencies -DincludeArtifactIds=fluo-recipes-core  -DoutputDirectory=$FLUO_APP_LIB
```

**Comment by keith-turner** [comment]
We may be able to get this down to one maven command also.  The docs for `includeArtifactIds` say it can be a comma separated list of artifact ids.
